import Vue from 'vue'
import { Icon, Button, Col, Row, Dropdown, DropdownMenu, DropdownItem, Carousel, CarouselItem, Pagination, Table, TableColumn, Form, FormItem, Input, Select, Option } from 'element-ui'
Vue.use(Icon)
Vue.use(Button)
Vue.use(Col)
Vue.use(Row)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Pagination)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Select)
Vue.use(Option)